name: Run tests

on: push

jobs:
  # Run tests in ubuntu
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: py -m unittest CalculatorTest.py
  # Run tests in windows
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: py -m unittest CalculatorTest.py
  # Run tests in macos
  test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: py -m unittest CalculatorTest.py